### ISSUE TITLE
Consider new YAML format standard

### ISSUE THREAD

**Issue by ryansb** [decause/hflossk#418]
Current YAML:

```
- blog: http://bridgeurl.com/danshumway-blogs
  feed: http://www.rssmix.com/u/3886341/rss.xml
  forges:
    - https://github.com/danShumway
    - http://bitbucket.org/danShumway
  irc: danShumway
  name: Daniel Shumway
  rit_dce: drs7453
  litreview1: http://blog.latinforimagination.com/lit-review-the-success-of-open-source-chpt-3/
  quiz1: http://blog.latinforimagination.com/quiz-writeup-principles-of-open-source/
  bugfix: http://danshumwayfoss.blogspot.com/2014/03/getting-started-with-contribution.html
  teamprop1: http://danshumwayfoss.blogspot.com/2014/03/team-proposal-monogame-community.html
  commarchreport: http://danshumwayfoss.blogspot.com/2014/03/monogame-community-architecture-analysis.html
  commarchpreso: http://tinyurl.com/pahtqvz
  curriculum: http://danshumwayfoss.blogspot.com/2014/04/common-core-standards-and-foss-game.html
  teamprop2: http://danshumwayfoss.blogspot.com/2014/04/team-proposal-python-math.html
  litreview2: http://danshumwayfoss.blogspot.com/2014/05/lit-review-common-fallacies.html
  quiz2: http://danshumwayfoss.blogspot.com/2014/05/quiz-lit-review.html
  hackathon1: http://blog.latinforimagination.com/wideeyes/
  playtesting: http://danshumwayfoss.blogspot.com/2014/05/playtesting-games-with-4th-graders.html
```

New yaml suggested by @liam-middlebrook in #416 

```
- blog: http://gearchicken.com/wordpress/
  feed: http://gearchicken.com/wordpress/?feed=rss
  forges:
    - http://github.com/liam-middlebrook
    - http://bitbucket.org/liam-middlebrook
  irc: loothelion
  name: Liam Middlebrook
  rit_dce: ljm2906
  hw:
    litreview1: http://gearchicken.com/wordpress/?p=17
    quiz1: http://gearchicken.com/wordpress/?p=20
    bugfix: http://gearchicken.com/wordpress/?p=33
    teamprop1: http://gearchicken.com/wordpress/?p=47
    commarchreport: http://gearchicken.com/wordpress/?p=57
    commarchpreso: http://gearchicken.com/commarch_hfoss.pdff
    curriculum: http://gearchicken.com/wordpress/?p=71
    teamprop2: http://gearchicken.com/wordpress/?p-76 # Isn't this covered in the projprop?
    litreview2: http://gearchicken.com/wordpress/?p=98
    quiz2: http://gearchicken.com/wordpress/?p=101
  bio: |
    This is a long string of text
    that I'm using as my personal biography on
    the RIT HFOSS site
  github: liam-middlebrook
  twitter: liammiddlebrook
  coderwall: liam-middlebrook
```

I like this change, but I have a couple suggestions.

First, the format extracts as `[{"blog": "...", "otherthing": "...}]`. I'd like to get rid of the 

```
- blog: ....
  otherthing: ....
```

And instead just have the format extract as a dictionary like `{"blog": "...", "name": "...."}`

```
blog: ...
name: ....
```

As an added bonus, every line wouldn't need a 2-space indentation.
