### ISSUE TITLE
One YAML to rule them all

### ISSUE THREAD

**Issue by decause** [decause/hflossk#473]
@msoucy @ryansb @liam-middlebrook 

There has been great controversy over standardizing the .yaml format for students. Here are some requirements:
1. Be as simple as possible. This repository is meant to be a **Teaching Tool**. Super-dee-duper engineering methods that improve performance or modularity are **secondary** to being easy to grok and edit. Keep this in mind at all times, even if it means a more inelegant solution in the long-run. I know, lame, but this is an _intro_ course, and onboarding is first priority.
2. Reduce duplication. Right now there is a place in <code>forges:</code> for a github repo, but it is also repeated later as a key of its own at the bottom of the file. Suboptimal.
3. Use as little nesting as possible. I know whitespace sensitivity is old-hat for pythonistas such as yourselves, but it is my #1 issue with newcomers. I would prefer to keep as many of the entries "top-level" as we can.

Let's hash out what a .yaml file might actually look like. I would _prefer_ not to have a <code>hw:</code> nested dictionary for assignments if we can help it.

**Comment by ryansb** [comment]
I agree that the YAML should be as simple as possible, but no simpler. Your students are primarily in technical majors or have technical interests, and as such I have total faith in their ability to handle nesting their homework assignments. I also think they would have a super easy time understanding YAML as a whole if given a proper introduction to terms like "list" and "key-value".

I imagine if you asked students organize their name, contact info, and assignments they would almost always make _two separate lists_, one for info about them, and one for their assignments. So the fact that their name and every assignment is at the same nesting level seems to me like it'd be _less_ onboarding-friendly. 

As for deduplicating the github/forges keys, sounds awesome! I think there may be value in getting rid of the `forges:` tag giving github a top-level key since I haven't seen any students put another forge there. @msoucy and @liam-middlebrook probably have opinions about that.

**Comment by liam-middlebrook** [comment]
I agree with @ryansb that there's a point at which the YAML is no longer at the point of easy and intuitive. You need to remember that this is an advanced elective, and arguably it's the easiest advanced elective in IGM. Asking students to learn a format like YAML that has a chance of helping them later in life is definitely not too much.

I also agree with @ryansb about the github deduplication. It's _very_ rare that a student has forges that aren't GitHub. And it's rare for students who do have multiple forges to use both consistently, [in example](https://bitbucket.org/liam-middlebrook)

I suggest the following rough YAML format:

``` YAML
blog: 
feed:
irc: 
name: 
rit_dce: 
hw:
  litreview1: 
  quiz1: 
  bugfix: 
  teamprop1: 
  commarchreport: 
  commarchpreso: 
  curriculum: 
  teamprop2: 
  litreview2: 
  quiz2: 

# Everything below this point is optional

bio: |
  This is a long string of text
  that I'm using as my personal biography on
  the RIT HFOSS site
github: 
twitter: 
coderwall: 
```

**Comment by ryansb** [comment]
As a note:

```
bio: |
  This is a long string of text
  that I'm using as my personal biography on
  the RIT HFOSS site
```

and

```
bio: A shorter bio
```

would be equivalent.

**Comment by decause** [comment]
```
blog: 
feed:
irc:
forges:
  - github.com/foobar
name: 
rit_dce: 
hw:
  litreview1: 
  quiz1: 
  bugfix: 
  teamprop1: 
  commarchreport: 
  commarchpreso: 
  curriculum: 
  teamprop2: 
  litreview2: 
  quiz2: 

# Everything below this point is optional

bio: |
  This is a long string of text
  that I'm using as my personal biography on
  the RIT HFOSS site
twitter: 
coderwall: 
```

**Comment by liam-middlebrook** [comment]
``` YAML
blog: 
feed:
irc:
github: foobar-username
name: 
rit_dce: 
hw:
  litreview1: 
  quiz1: 
  bugfix: 
  teamprop1: 
  commarchreport: 
  commarchpreso: 
  curriculum: 
  teamprop2: 
  litreview2: 
  quiz2: 

# Everything below this point is optional

bio: |
  This is a long string of text
  that I'm using as my personal biography on
  the RIT HFOSS site
twitter: 
coderwall: 
```

I think it would be much simpler to just have the github as a required key. Plus that could potentially be used for some automation later in the future of hflossk.

**Comment by ryansb** [comment]
The downside of having github as a required key separate from forges are:
1. We don't want to promote github to the exclusion of other forges
2. We can always parse the URL out of forges easily (that's what `urllib3` is for!)
3. People are going to show off other projects or bugfixes from other forges

**Comment by msoucy** [comment]
As proof that people will use different forges, my latest project is on my custom hosted forge. GitHub is only special because of the community, and other forges should be equally accepted by this course

**Comment by decause** [comment]
So, from what it looks like in the conversation above, the new model has a list for forges (with Github being a member there), and a dictionary for hw assignments as shown below. Please confirm @ryansb @liam-middlebrook @msoucy 

```
blog: 
feed:
irc:
forges:
  - github.com/foobar
name: 
rit_dce: 
hw:
  litreview1: 
  quiz1: 
  bugfix: 
  teamprop1: 
  commarchreport: 
  commarchpreso: 
  curriculum: 
  teamprop2: 
  litreview2: 
  quiz2: 
# Everything below this point is optional
bio: |
  This is a long string of text
  that I'm using as my personal biography on
  the RIT HFOSS site
twitter: 
coderwall: 
```
