### ISSUE TITLE
XSS in the participants page

### ISSUE THREAD

**Issue by dxa4481** [decause/hflossk#566]
This is sort of a low level issue because all Yaml files are manually inspected before being accepted however there is no output encoding being done on the yaml files what so ever. Here is one example of what a student can do

``` yaml
blog: http://attacker.blogspot.com/"><script>alert('1')</script>
feed: http://attacker.blogspot.com/feeds/posts/default?alt=rss"><script>alert('1')</script>
forges:
  - https://github.com/attacker
irc: attacker
name: attacker
```

Note that any of the fields above can be injected, I just put it in the blog and feed URIs to drive the point home. 

Just in case someone doesn't believe me, here's a [screenshot](http://i.imgur.com/DdqKVJI.png)
